CREATE TABLE Result (
	Id BIGINT NOT NULL PRIMARY KEY,
	BestLap BIGINT NOT NULL,
	BestSplitsId BIGINT NOT NULL,
	IsWetSession BIT NOT NULL,
	Type BIGINT NOT NULL,
	FOREIGN KEY (BestSplitsId) REFERENCES Splits(Id)
);
