CREATE TABLE Timing (
	Id BIGINT NOT NULL PRIMARY KEY,
	LastLap BIGINT NOT NULL,
	LastSplitsId BIGINT NOT NULL,
	BestLap BIGINT NOT NULL,
	BestSplitsId BIGINT NOT NULL,
	TotalTime BIGINT NOT NULL,
	LapCount BIGINT NOT NULL,
	LastSplitId BIGINT NOT NULL,
	FOREIGN KEY (LastSplitsId) REFERENCES Splits(Id),
	FOREIGN KEY (BestSplitsId) REFERENCES Splits(Id)
);
